### ISSUE TITLE
I need to be able to create an open pod.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#131]
I need to be able to create a pod that is open. That have no network rules.
Right now it at least have the default rules that means that is closes. And its very hard to setup anything in a closed pod.

**Comment by Unicus-Tom** [comment]
Feature has been added but one bug remains. To enable internet again you also need to make a change in the rules. Working on fixing the logic

**Comment by Unicus-Tom** [comment]
Previous issue has been fixed. So this should be ready for closing once the merge has been approved.
