### ISSUE TITLE
Port of gendered rules in the wrong location.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#133]
For Incoming rules:
The ip end up in the right location but the port should be in Destination Port Ranges not Source port Rages. (Yes i know it makes no sense unless your a networking guru. )
Outgoing rules it seem correct.

You almost never do anything with the Source Port as that often an auto generated high port for that one connection.

**Comment by Unicus-Tom** [comment]
This should have been fixed in 3e8e3d8002cf9838ace235bb007c8a6e32dba862
