### ISSUE TITLE
Back-end deployment

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#23]
Setup the full pipeline and have a working deployment to staging using the system created in #11.

I would recommend looking into Container instances. Its a very easy way to get docker image running inside azure. Https support is a requirement and is going to be annoying to work with.
Pro tip [Let’s Encrypt](https://letsencrypt.org/)is your friend here.

I would be surprised if we end up using Container instances for sepes hosting. But right now i think its the eayest way to get started.

**Comment by einaren** [comment]
Sepes is now hosted in Radix. closing
