### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by Unicus-Tom** [equinor/sepes-api#31]
Simplify the configuration needed for each system.

**Comment by Unicus-Tom** [comment]
RestAPI instrumentation key: Currently only supports dotnet secret storage.

**Comment by gjersvik** [comment]
Need to sleep on if we need it as part of the MVP. One instrumentation key two places is an acceptable pain for now.

**Comment by gjersvik** [comment]
Now there is a bit more than one instrumentation key in to places and the configuration is staring to become a bit messy as keys are just added with features and we need a strategy here.
