### ISSUE TITLE
Review access_control.md

### ISSUE THREAD

**Issue by krsteen** [equinor/sepes-api#314]
Document can be found here: https://github.com/equinor/sepes-web/blob/master/docs/access_control.md

**Actions:**
View all unrestricted studies: All equinor users can do this
New Action: Reassign owner?

Missing actions:

**Roles**
Study Owner (the one that created the study)
If Admin should not be allowed to view ALL studies, should we have a Developer Role?
Missing roles: Study owner

**Comment by krsteen** [comment]
Document can be found at https://github.com/equinor/sepes-web/blob/master/docs/access_control.md

**Comment by einaren** [comment]
Duplicate of equinor/sepes-internal/#7
