### ISSUE TITLE
VM: Should Region follow Sandbox region, or should it be customizeable

### ISSUE THREAD

**Issue by krsteen** [equinor/sepes-api#347]
Right now, the VM is created in the region specified in the Create request. Should this be possible? Does it make sense to create it in another region than the rest? If so, we need a lookup in the VM create dialog

**Comment by krsteen** [comment]
@christertime Do you have any views on this?

**Comment by christertime** [comment]
You can't join a VM to a VNET that is in another region, so those always have to be the same.
