### ISSUE TITLE
Backend: Finalize tokens

### ISSUE THREAD

**Issue by Unicus-Tom** [equinor/sepes-api#38]
Currently tokens are loosely implemented. So we need to judge what parameters the two tokens need. Afterwards logic needs to be written to populate these parameters and to authenticate the azure login token.
Framework for these are marked in the code with the issue number in comments. Search "Issue: 38" to find them.

Also look into the viability of using a single class internaly to represent both tokens (AzTokenClass and SepesTokenClass).

**Comment by einaren** [comment]
Obsolete task. Closing
