### ISSUE TITLE
Back-end Archive Study

### ISSUE THREAD

**Issue by Unicus-Tom** [equinor/sepes-api#46]
- [x] The client can mark a study as archived and not.
- [x] Backed will not return archived studies by default.
- [x] Have a special handler to get archived studies. "/study/archived" for example.

**Comment by kribjo1968** [comment]
Agreed in meeting (testlab) with Equinor Delete Study is not MVP.

**Comment by gjersvik** [comment]
We have decided that delete study is out of scope for an MVP. Archiving is a lot simpler to deal with and should be in scope for now.
