### ISSUE TITLE
Backend/Frontend Searching

### ISSUE THREAD

**Issue by Unicus-Tom** [equinor/sepes-api#49]
Setting this as seperate issue as it goes across both sides (auto complete as you type) and might be a bit complex. Ties in with #47. 

Either backend or frontend takes care of all sorting. Or we might go for a hybrid solution, like for example having the frontend request emails based on the first letter entered, then getting a list of all emails starting with that email and using it to search locally.

Pre-requisite: Tag for selection in AD. as discussed in last meeting at Equinor.

**Comment by Unicus-Tom** [comment]
I think the best approach to this would be to let the backend do all the searching, but set up front end so the request for search is not send until (30-100 ms) after first character is entered or last search done.
This seems to be similar to how other live search bars operate,

**Comment by Unicus-Tom** [comment]
As it has not yet been decided how we will implement searching I have added backend search functions that can query the current database model. No front end work as of now.

**Comment by einaren** [comment]
Obsolete task. Closing
