### ISSUE TITLE
Write dev test tooling.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#67]
Write tooling in top level folder that makes it easier to run, build and test all sub project from one place.
- [ ] Top level build. "npm build"
- [ ] Run all tests "npm test"
- [ ] Add code coverage report to tests.
- [ ] "npm starts" starts a devtest sever with back and front end as one simple command. Using minimal configuration.

**Comment by einaren** [comment]
Obsolete task. Closing
