### ISSUE TITLE
Dockerize everything.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#68]
Create docker files for etch component used by sepes. And a docker compose file to run a full local dev environment.

- [ ] Dockerize frontend.
- [ ] Dockerize backend.
- [ ] Dockerize database.
- [ ] Dockerize opa.
- [ ] docker compose.

Then you can start sepes with a simple "docker-compose up"
It must work on windows.

**Comment by einaren** [comment]
Obsolete task. Closing
