### ISSUE TITLE
Setup common resources.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#69]
Have sepes check and if needed create the following resources at boot.
* One resource group for sepes manged resources like networks.
* One [custom roles](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles) that allows a read a network settings and join it but nothing else.

Also all resource need to be prefixed so that multiple sepes environments can run in the same subscription.

- [x] Make sure the resource group exist if not create it.
- [ ] Make sure that there exist a custom role and if not create it.

**Comment by gjersvik** [comment]
Created issue #95 to deal with part of this task we found to hard for now.

**Comment by kribjo1968** [comment]
"Make sure that there exist a custom role and if not create it."

- Kristoffer and Ole Martin have agreed that this custom role is to be set manually in Azure.
