### ISSUE TITLE
Issue when rapidly creating sandbox after changing from invalid wbs to valid wbs

### ISSUE THREAD

**Issue by HansKristianVikOlsen** [equinor/sepes-api#728]
This can only be reproduced in the API

Temporarely fix:
Either show the loading screen after Study save, or perhaps disable the "Create sandbox" and "Create dataset" buttons immediately after Study is saved, and then enable it again after request returns.

1. Create sandbox with invalid wbs
2. Change to valid wbs
3. Quickly create a sandbox and you get an error

**Comment by HansKristianVikOlsen** [comment]
This is done on the web app for sepes as a temporary fix

**Comment by einaren** [comment]
Ikke et nevneverdig problem. lukker denne og ser om vi får bug fra bruker
