### ISSUE TITLE
Pod Network security group

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#73]
Create and sync [Network security group](https://docs.microsoft.com/en-us/azure/virtual-network/security-overview) based on pod models. Using the address and port array to generate rules for incoming and outgoing traffic, and applying them to a security group. And finally applying the security group to a subnet.

- [x] Create new security groups based on models.
- [x] Apply and remove security group on a subnet. 
- [x] Move from one group to another without any time where its totally open.
- [x] Remove unused security groups.

**Comment by Unicus-Tom** [comment]
Backend part of this complete, awaiting code review
