### ISSUE TITLE
SEPES Study Details View UI

### ISSUE THREAD

**Issue by kribjo1968** [equinor/sepes-api#76]
In the left pane there are two similar lists, one for sponsors and one for suppliers. Both allow you to add more sponsors/suppliers. Currently there are no documented rules for whom should be added or not.

Below are the dataset list where checked rows are the datasets to be used.

Right (main) pane shows all the configured POD's and the abilidy to create more POD's.

![SEPES-Study-Name_of_Study](https://user-images.githubusercontent.com/10142715/66200003-49462380-e6a0-11e9-9edb-9651b2e601a7.png)

**Comment by gjersvik** [comment]
I find calling this the pod main ui is confusing to me. Its more of a study details view.
When i think pod main ui i am thinking about the view where you sett pod settings.
