### ISSUE TITLE
Can't fetch current IP when adding network rules

### ISSUE THREAD

**Issue by christertime** [equinor/sepes-api#827]
Getting an error when selecting current personal IP in the dropdown when creating new inbound rule for a VM
![bilde](https://user-images.githubusercontent.com/51078392/156757352-64d42a7e-ec93-434d-8b66-86c7cb67672d.png)

**Comment by bonyfusbouvet** [comment]
@christertime this is because of uBlock adblocker. If you disable the extension, it works. Not sure we can do anything about it.

**Comment by bonyfusbouvet** [comment]
This is because of the uBlock add blocker.
