### ISSUE TITLE
Setup log system.

### ISSUE THREAD

**Issue by gjersvik** [equinor/sepes-api#9]
Deploy the first version of a system that can take logs form both browser clients and backed services.

I would recommend just look at https://docs.microsoft.com/en-us/azure/azure-monitor/azure-monitor-log-hub as a simple cloud native solution.

Do not need to automate the creation of a motoring service at this point. Lets get more azure experience before we try to automate everything.

**Comment by Unicus-Tom** [comment]
We have chosen to likely use Azures own monitoring service. This requires no backend set up so ticket can be considered complete.

Keeping open until restapi and frontend log and monitor is done
